"""
THIS TESTS WHERE NOT CREATED AS THERE'S CURRENTLY NO DATABASE OPERATIONS TO BE PERFORMED BY THE
TASK APP AND WE CONSIDER THAT THE LOGIC OF THE MODEL IS TOO SIMPLE FOR ITS TEST TO BE A PRIORITY.
test_models contains all the tests related to the models defined within
the tasks app.
"""


